In [98]:
## import libraries

import pandas as pd
import numpy as np
import datetime
import yfinance as yf

from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl import config_tickers
from finrl.config import INDICATORS

import itertools

In [99]:
TRAIN_START_DATE = '2009-01-01'
TRAIN_END_DATE = '2020-07-01'
TRADE_START_DATE = '2020-07-01'
TRADE_END_DATE = '2022-12-01'

symbols = [
    'aapl',
    'msft',
    'meta',
    'ibm',
    'hd',
    'cat',
    'amzn',
    'intc',
    't',
    'v'
    'gs'
]

In [100]:
df_raw = YahooDownloader(start_date = TRAIN_START_DATE,
                                end_date = TRADE_END_DATE,
                                ticker_list = symbols).fetch_data()

C:\Users\ASUS\Desktop\Finance\RL\venv\lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed
C:\Users\ASUS\Desktop\Finance\RL\venv\lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed
C:\Users\ASUS\Desktop\Finance\RL\venv\lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[************

Shape of DataFrame:  (32040, 8)


In [101]:
df_raw.head()

date       open       high        low      close     volume   tic  \
0  2009-01-02   3.067143   3.251429   3.041429   2.747390  746015200  aapl   
1  2009-01-02   2.567500   2.726500   2.553500   2.718000  145928000  amzn   
2  2009-01-02  44.910000  46.980000  44.709999  30.950012    7117200   cat   
3  2009-01-02  23.070000  24.190001  22.959999  16.649143   14902500    hd   
4  2009-01-02  80.200768  83.738052  80.200768  50.100773    7905877   ibm   

   day  
0    4  
1    4  
2    4  
3    4  
4    4

In [102]:
fe = FeatureEngineer(use_technical_indicator=True,
                     tech_indicator_list = INDICATORS,
                     use_vix=True,
                     use_turbulence=True,
                     user_defined_feature = False)

processed = fe.preprocess_data(df_raw)

Successfully added technical indicators


C:\Users\ASUS\Desktop\Finance\RL\venv\lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed


Shape of DataFrame:  (3502, 8)
Successfully added vix
Successfully added turbulence index


In [103]:
processed

date        open        high         low       close     volume  \
0      2009-01-02    3.067143    3.251429    3.041429    2.747390  746015200   
1      2009-01-02    2.567500    2.726500    2.553500    2.718000  145928000   
2      2009-01-02   44.910000   46.980000   44.709999   30.950012    7117200   
3      2009-01-02   23.070000   24.190001   22.959999   16.649143   14902500   
4      2009-01-02   80.200768   83.738052   80.200768   50.100773    7905877   
...           ...         ...         ...         ...         ...        ...   
28011  2022-11-29  316.000000  320.000000  315.619995  305.557312    3505600   
28012  2022-11-29  145.910004  147.169998  145.699997  139.558807    2754700   
28013  2022-11-29   28.850000   29.180000   28.740000   28.240854   24361500   
28014  2022-11-29  241.399994  242.789993  238.210007  238.217743   17956300   
28015  2022-11-29   18.790001   19.030001   18.750000   17.527452   24088000   

        tic  day      macd     boll_ub     boll_lb      rsi_30     cci_30  \
0      aapl    4  0.000000    2.969346    2.641385  100.000000  66.666667   
1      amzn    4  0.000000    2.969346    2.641385  100.000000  66.666667   
2       cat    4  0.000000    2.969346    2.641385  100.000000  66.666667   
3        hd    4  0.000000    2.969346    2.641385  100.000000  66.666667   
4       ibm    4  0.000000    2.969346    2.641385  100.000000  66.666667   
...     ...  ...       ...         ...         ...         ...        ...   
28011    hd    1  8.491188  324.439971  268.177372   56.444578  83.144966   
28012   ibm    1  4.523366  145.729322  125.716428   63.696291  83.912091   
28013  intc    1  0.435235   30.506556   26.224579   49.010665  33.364885   
28014  msft    1  2.267116  254.737121  213.164572   49.156757  34.946232   
28015     t    1  0.446189   17.881416   16.719863   60.467981  64.832371   

            dx_30  close_30_sma  close_60_sma        vix  turbulence  
0      100.000000      2.747390      2.747390  39.189999    0.000000  
1      100.000000      2.718000      2.718000  39.189999    0.000000  
2      100.000000     30.950012     30.950012  39.189999    0.000000  
3      100.000000     16.649143     16.649143  39.189999    0.000000  
4      100.000000     50.100773     50.100773  39.189999    0.000000  
...           ...           ...           ...        ...         ...  
28011   22.103961    289.574117    280.954247  21.889999    3.949013  
28012   42.080709    131.775917    124.174526  21.889999    3.949013  
28013    0.768171     27.603657     27.243324  21.889999    3.949013  
28014    0.428685    234.291056    237.173987  21.889999    3.949013  
28015   20.258599     16.852541     15.702813  21.889999    3.949013  

[28016 rows x 18 columns]

In [104]:
list_ticker = processed["tic"].unique().tolist()
list_date = list(pd.date_range(processed['date'].min(),processed['date'].max()).astype(str))
combination = list(itertools.product(list_date,list_ticker))

processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(processed,on=["date","tic"],how="left")
processed_full = processed_full[processed_full['date'].isin(processed['date'])]
processed_full = processed_full.sort_values(['date','tic'])

processed_full = processed_full.fillna(0)

In [105]:
processed_full

date   tic        open        high         low       close  \
0      2009-01-02  aapl    3.067143    3.251429    3.041429    2.747390   
1      2009-01-02  amzn    2.567500    2.726500    2.553500    2.718000   
2      2009-01-02   cat   44.910000   46.980000   44.709999   30.950012   
3      2009-01-02    hd   23.070000   24.190001   22.959999   16.649143   
4      2009-01-02   ibm   80.200768   83.738052   80.200768   50.100773   
...           ...   ...         ...         ...         ...         ...   
40635  2022-11-29    hd  316.000000  320.000000  315.619995  305.557312   
40636  2022-11-29   ibm  145.910004  147.169998  145.699997  139.558807   
40637  2022-11-29  intc   28.850000   29.180000   28.740000   28.240854   
40638  2022-11-29  msft  241.399994  242.789993  238.210007  238.217743   
40639  2022-11-29     t   18.790001   19.030001   18.750000   17.527452   

            volume  day      macd     boll_ub     boll_lb      rsi_30  \
0      746015200.0  4.0  0.000000    2.969346    2.641385  100.000000   
1      145928000.0  4.0  0.000000    2.969346    2.641385  100.000000   
2        7117200.0  4.0  0.000000    2.969346    2.641385  100.000000   
3       14902500.0  4.0  0.000000    2.969346    2.641385  100.000000   
4        7905877.0  4.0  0.000000    2.969346    2.641385  100.000000   
...            ...  ...       ...         ...         ...         ...   
40635    3505600.0  1.0  8.491188  324.439971  268.177372   56.444578   
40636    2754700.0  1.0  4.523366  145.729322  125.716428   63.696291   
40637   24361500.0  1.0  0.435235   30.506556   26.224579   49.010665   
40638   17956300.0  1.0  2.267116  254.737121  213.164572   49.156757   
40639   24088000.0  1.0  0.446189   17.881416   16.719863   60.467981   

          cci_30       dx_30  close_30_sma  close_60_sma        vix  \
0      66.666667  100.000000      2.747390      2.747390  39.189999   
1      66.666667  100.000000      2.718000      2.718000  39.189999   
2      66.666667  100.000000     30.950012     30.950012  39.189999   
3      66.666667  100.000000     16.649143     16.649143  39.189999   
4      66.666667  100.000000     50.100773     50.100773  39.189999   
...          ...         ...           ...           ...        ...   
40635  83.144966   22.103961    289.574117    280.954247  21.889999   
40636  83.912091   42.080709    131.775917    124.174526  21.889999   
40637  33.364885    0.768171     27.603657     27.243324  21.889999   
40638  34.946232    0.428685    234.291056    237.173987  21.889999   
40639  64.832371   20.258599     16.852541     15.702813  21.889999   

       turbulence  
0        0.000000  
1        0.000000  
2        0.000000  
3        0.000000  
4        0.000000  
...           ...  
40635    3.949013  
40636    3.949013  
40637    3.949013  
40638    3.949013  
40639    3.949013  

[28016 rows x 18 columns]

In [106]:
# Split the data
train = data_split(processed_full, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full, TRADE_START_DATE,TRADE_END_DATE)
print(len(train))
print(len(trade))

23144
4872


In [107]:
data_path = '../data/'
train_path = data_path + 'candles/train.csv'
trade_path = data_path + 'candles/trade.csv'

In [108]:
with open(train_path, 'w', encoding = 'utf-8-sig') as f:
  train.to_csv(f)
  f.close()
with open(trade_path, 'w', encoding = 'utf-8-sig') as f:
  trade.to_csv(f)
  f.close()

In [109]:
######################################################################
##############################   SECTION2   ##########################
######################################################################

from finrl.meta.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.agents.stablebaselines3.models import DRLAgent
from stable_baselines3.common.logger import configure
from finrl import config_tickers
from finrl.main import check_and_make_directories
from finrl.config import INDICATORS, TRAINED_MODEL_DIR, RESULTS_DIR

In [110]:
stock_dimension = len(train.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 8, State Space: 81


In [111]:
buy_cost_list = sell_cost_list = [0.001] * stock_dimension
num_stock_shares = [0] * stock_dimension

env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "num_stock_shares": num_stock_shares,
    "buy_cost_pct": buy_cost_list,
    "sell_cost_pct": sell_cost_list,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4
}


e_train_gym = StockTradingEnv(df = train, **env_kwargs)

In [112]:
env_train, _ = e_train_gym.get_sb_env()
print(type(env_train))

<class 'stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv'>


In [144]:
agent = DRLAgent(env = env_train)

# Set the corresponding values to 'True' for the algorithms that you want to use
if_using_a2c = True
if_using_ddpg = True
if_using_ppo = True
if_using_td3 = True
if_using_sac = True

In [114]:
# A2C Agent

model_a2c = agent.get_model("a2c")
model_ddpg = agent.get_model('ddpg')
model_ppo = agent.get_model('ppo')
model_td3 = agent.get_model('td3')
model_sac = agent.get_model('sac')

if if_using_a2c:
  # set up logger
  tmp_path = RESULTS_DIR + '/a2c'
  new_logger_a2c = configure(tmp_path, ["stdout", "csv", "tensorboard"])
  # Set new logger
  model_a2c.set_logger(new_logger_a2c)

if if_using_ddpg:
  # set up logger
  tmp_path = RESULTS_DIR + '/ddpg'
  new_logger_ddpg = configure(tmp_path, ["stdout", "csv", "tensorboard"])
  # Set new logger
  model_ppo.set_logger(new_logger_ddpg)

if if_using_ppo:
  # set up logger
  tmp_path = RESULTS_DIR + '/ppo'
  new_logger_ppo = configure(tmp_path, ["stdout", "csv", "tensorboard"])
  # Set new logger
  model_ppo.set_logger(new_logger_ppo)

if if_using_td3:
  # set up logger
  tmp_path = RESULTS_DIR + '/td3'
  new_logger_td3 = configure(tmp_path, ["stdout", "csv", "tensorboard"])
  # Set new logger
  model_ppo.set_logger(new_logger_td3)

if if_using_sac:
  # set up logger
  tmp_path = RESULTS_DIR + '/sac'
  new_logger_sac = configure(tmp_path, ["stdout", "csv", "tensorboard"])
  # Set new logger
  model_ppo.set_logger(new_logger_sac)



{'n_steps': 5, 'ent_coef': 0.01, 'learning_rate': 0.0007}
Using cpu device
{'batch_size': 128, 'buffer_size': 50000, 'learning_rate': 0.001}
Using cpu device
{'n_steps': 2048, 'ent_coef': 0.01, 'learning_rate': 0.00025, 'batch_size': 64}
Using cpu device
{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001}
Using cpu device
{'batch_size': 64, 'buffer_size': 100000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1'}
Using cpu device
Logging to results/a2c
Logging to results/ddpg
Logging to results/ppo
Logging to results/td3
Logging to results/sac


In [115]:
trained_a2c = agent.train_model(model=model_a2c,
                             tb_log_name='a2c',
                             total_timesteps=50000) if if_using_a2c else None

trained_ddpg = agent.train_model(model=model_ddpg,
                             tb_log_name='ddpg',
                             total_timesteps=50000) if if_using_ddpg else None

trained_ppo = agent.train_model(model=model_ppo,
                             tb_log_name='ppo',
                             total_timesteps=50000) if if_using_ppo else None

trained_td3 = agent.train_model(model=model_td3,
                             tb_log_name='td3',
                             total_timesteps=50000) if if_using_td3 else None

trained_sac = agent.train_model(model=model_sac,
                             tb_log_name='sac',
                             total_timesteps=50000) if if_using_sac else None

---------------------------------------
| time/                 |             |
|    fps                | 243         |
|    iterations         | 100         |
|    time_elapsed       | 2           |
|    total_timesteps    | 500         |
| train/                |             |
|    entropy_loss       | -11.5       |
|    explained_variance | -0.0161     |
|    learning_rate      | 0.0007      |
|    n_updates          | 99          |
|    policy_loss        | 14.8        |
|    reward             | -0.68778497 |
|    std                | 1.01        |
|    value_loss         | 2.85        |
---------------------------------------
--------------------------------------
| time/                 |            |
|    fps                | 244        |
|    iterations         | 200        |
|    time_elapsed       | 4          |
|    total_timesteps    | 1000       |
| train/                |            |
|    entropy_loss       | -11.5      |
|    explained_variance | 0          |
|    lear

In [145]:
trained_td3 = agent.train_model(model=model_td3,
                             tb_log_name='td3',
                             total_timesteps=50000) if if_using_td3 else None

trained_sac = agent.train_model(model=model_sac,
                             tb_log_name='sac',
                             total_timesteps=50000) if if_using_sac else None

----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 58        |
|    time_elapsed    | 198       |
|    total_timesteps | 11572     |
| train/             |           |
|    actor_loss      | 219       |
|    critic_loss     | 139       |
|    learning_rate   | 0.001     |
|    n_updates       | 63626     |
|    reward          | 3.6894298 |
----------------------------------
day: 2892, episode: 100
begin_total_asset: 1000000.00
end_total_asset: 3733721.75
total_reward: 2733721.75
total_cost: 999.00
total_trades: 2892
Sharpe: 0.550
----------------------------------
| time/              |           |
|    episodes        | 8         |
|    fps             | 58        |
|    time_elapsed    | 393       |
|    total_timesteps | 23144     |
| train/             |           |
|    actor_loss      | 152       |
|    critic_loss     | 314       |
|    learning_rate   | 0.001     |
|    n_updates       | 75198     |
|

In [149]:
print(type(trained_td3))
print(type(trained_sac))

<class 'stable_baselines3.td3.td3.TD3'>
<class 'stable_baselines3.sac.sac.SAC'>


In [150]:
# Save trained model
trained_a2c.save(data_path + "agents/agent_a2c") if if_using_a2c else None
trained_ddpg.save(data_path + "agents/agent_ddpg") if if_using_ddpg else None
trained_ppo.save(data_path + "agents/agent_ppo") if if_using_ppo else None
trained_td3.save(data_path + "agents/agent_td3") #if if_using_td3 else None
trained_sac.save(data_path + "agents/agent_sac") #if if_using_sac else None
print(type(trained_td3))
print(type(trained_sac))

<class 'stable_baselines3.td3.td3.TD3'>
<class 'stable_baselines3.sac.sac.SAC'>


In [151]:
######################################################################
##############################   SECTION3   ##########################
######################################################################

train = train.set_index(train.columns[0])
train.index.names = ['']
trade = trade.set_index(trade.columns[0])
trade.index.names = ['']

In [152]:
if_using_a2c = True
if_using_ddpg = True
if_using_ppo = True
if_using_td3 = True
if_using_sac = True

In [153]:
from stable_baselines3 import A2C, DDPG, PPO, SAC, TD3

trained_a2c = A2C.load(data_path + 'agents/agent_a2c') if if_using_a2c else None
trained_ddpg = DDPG.load(data_path + "agents/agent_ddpg") if if_using_ddpg else None
trained_ppo = PPO.load(data_path + "agents/agent_ppo") if if_using_ppo else None
trained_td3 = TD3.load(data_path + "agents/agent_td3") if if_using_td3 else None
trained_sac = SAC.load(data_path + "agents/agent_sac") if if_using_sac else None

In [154]:
stock_dimension = len(trade.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 8, State Space: 81


In [155]:
buy_cost_list = sell_cost_list = [0.001] * stock_dimension
num_stock_shares = [0] * stock_dimension

# print(num_stock_shares)
# print(buy_cost_list)
# print(sell_cost_list)
# print(state_space)
# print(stock_dimension)
# print(INDICATORS)
# print(stock_dimension)

env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "num_stock_shares": num_stock_shares,
    "buy_cost_pct": buy_cost_list,
    "sell_cost_pct": sell_cost_list,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4
}

In [156]:
train = data_split(processed_full, TRAIN_START_DATE,TRAIN_END_DATE)
trade = data_split(processed_full, TRADE_START_DATE,TRADE_END_DATE)
print(trade)

           date   tic        open        high         low       close  \
0    2020-07-01  aapl   91.279999   91.839996   90.977501   89.133003   
0    2020-07-01  amzn  137.899506  144.750000  137.699997  143.934998   
0    2020-07-01   cat  129.380005  129.399994  125.879997  116.095177   
0    2020-07-01    hd  249.649994  250.330002  246.929993  228.232849   
0    2020-07-01   ibm  114.980881  115.898659  113.164436   95.288437   
..          ...   ...         ...         ...         ...         ...   
608  2022-11-29    hd  316.000000  320.000000  315.619995  305.557312   
608  2022-11-29   ibm  145.910004  147.169998  145.699997  139.558807   
608  2022-11-29  intc   28.850000   29.180000   28.740000   28.240854   
608  2022-11-29  msft  241.399994  242.789993  238.210007  238.217743   
608  2022-11-29     t   18.790001   19.030001   18.750000   17.527452   

          volume  day      macd     boll_ub     boll_lb     rsi_30  \
0    110737200.0  2.0  2.988731   91.903729   79.4918

In [157]:

e_trade_gym = StockTradingEnv(df = trade, turbulence_threshold = 70,risk_indicator_col='vix', **env_kwargs)
# env_trade, obs_trade = e_trade_gym.get_sb_env()e_trade_gym = StockTradingEnv(df = trade, **env_kwargs)

In [158]:
df_account_value_a2c, df_actions_a2c = DRLAgent.DRL_prediction(
    model=trained_a2c,
    environment = e_trade_gym) if if_using_a2c else (None, None)

df_account_value_ddpg, df_actions_ddpg= DRLAgent.DRL_prediction(
    model=trained_ddpg,
    environment = e_trade_gym) if if_using_ddpg else (None, None)

df_account_value_ppo, df_actions_ppo = DRLAgent.DRL_prediction(
    model=trained_ppo,
    environment = e_trade_gym) if if_using_ppo else (None, None)

df_account_value_td3, df_actions_td3 = DRLAgent.DRL_prediction(
    model=trained_td3,
    environment = e_trade_gym) if if_using_td3 else (None, None)

df_account_value_sac, df_actions_sac = DRLAgent.DRL_prediction(
    model=trained_sac,
    environment = e_trade_gym) if if_using_sac else (None, None)

hit end!
hit end!
hit end!
hit end!
hit end!


In [159]:
# Mean Variance Optimization

# Helps us process data into a form for weight calculation
def process_df_for_mvo(df):
  df = df.sort_values(['date','tic'],ignore_index=True)[['date','tic','close']]
  fst = df
  fst = fst.iloc[0:stock_dimension, :]
  tic = fst['tic'].tolist()

  mvo = pd.DataFrame()

  for k in range(len(tic)):
    mvo[tic[k]] = 0

  for i in range(df.shape[0]//stock_dimension):
    n = df
    n = n.iloc[i * stock_dimension:(i+1) * stock_dimension, :]
    date = n['date'][i*stock_dimension]
    mvo.loc[date] = n['close'].tolist()

  return mvo

# Calculates weights of average return and covariance matrix
def StockReturnsComputing(StockPrice, Rows, Columns):
  import numpy as np
  StockReturn = np.zeros([Rows-1, Columns])
  for j in range(Columns):        # j: Assets
    for i in range(Rows-1):     # i: Daily Prices
      StockReturn[i,j]=((StockPrice[i+1, j]-StockPrice[i,j])/StockPrice[i,j])* 100

  return StockReturn

In [160]:
StockData = process_df_for_mvo(train)
TradeData = process_df_for_mvo(trade)

TradeData.to_numpy()

array([[ 89.133, 143.935, 116.095, ...,  53.128, 198.346,  16.805],
       [ 89.133, 144.515, 117.624, ...,  53.417, 199.858,  16.906],
       [ 91.517, 152.852, 119.199, ...,  53.787, 204.16 ,  17.136],
       ...,
       [147.287,  93.41 , 229.906, ...,  28.671, 245.315,  17.629],
       [143.418,  93.95 , 226.59 , ...,  28.075, 239.635,  17.352],
       [140.385,  92.42 , 229.341, ...,  28.241, 238.218,  17.527]])

In [161]:
#compute asset returns
arStockPrices = np.asarray(StockData)
[Rows, Cols]=arStockPrices.shape
arReturns = StockReturnsComputing(arStockPrices, Rows, Cols)

#compute mean returns and variance covariance matrix of returns
meanReturns = np.mean(arReturns, axis = 0)
covReturns = np.cov(arReturns, rowvar=False)

#set precision for printing results
np.set_printoptions(precision=3, suppress = True)

#display mean returns and variance-covariance matrix of returns
print('Mean returns of assets in k-portfolio 1\n', meanReturns)
print('Variance-Covariance matrix of returns\n', covReturns)

Mean returns of assets in k-portfolio 1
 [0.136 0.158 0.066 0.103 0.033 0.076 0.103 0.038]
Variance-Covariance matrix of returns
 [[3.156 1.592 1.722 1.303 1.218 1.674 1.561 0.876]
 [1.592 4.533 1.657 1.299 1.158 1.516 1.808 0.761]
 [1.722 1.657 4.019 1.577 1.513 1.929 1.711 1.187]
 [1.303 1.299 1.577 2.373 1.166 1.501 1.366 0.953]
 [1.218 1.158 1.513 1.166 2.052 1.399 1.296 0.944]
 [1.674 1.516 1.929 1.501 1.399 3.289 1.9   1.034]
 [1.561 1.808 1.711 1.366 1.296 1.9   2.759 0.916]
 [0.876 0.761 1.187 0.953 0.944 1.034 0.916 1.577]]


In [162]:
from pypfopt.efficient_frontier import EfficientFrontier

ef_mean = EfficientFrontier(meanReturns, covReturns, weight_bounds=(0, 0.5))
raw_weights_mean = ef_mean.max_sharpe()
cleaned_weights_mean = ef_mean.clean_weights()
mvo_weights = np.array([1000000 * cleaned_weights_mean[i] for i in range(8)])

mvo_weights

array([412090., 358860.,      0., 229050.,      0.,      0.,      0.,
            0.])

In [163]:
LastPrice = np.array([1/p for p in StockData.tail(1).to_numpy()[0]])
Initial_Portfolio = np.multiply(mvo_weights, LastPrice)

Initial_Portfolio

array([4614.571, 2601.547,    0.   ,  994.126,    0.   ,    0.   ,
          0.   ,    0.   ])

In [164]:
Portfolio_Assets = TradeData @ Initial_Portfolio
MVO_result = pd.DataFrame(Portfolio_Assets, columns=["Mean Var"])

MVO_result

Mean Var
2020-07-01  1.012656e+06
2020-07-02  1.014485e+06
2020-07-06  1.048137e+06
2020-07-07  1.037411e+06
2020-07-08  1.059415e+06
...                  ...
2022-11-22  1.243966e+06
2022-11-23  1.247230e+06
2022-11-25  1.236456e+06
2022-11-28  1.212838e+06
2022-11-29  1.192015e+06

[609 rows x 1 columns]

In [165]:
# DOW JONES Index as Another Baseline

TRAIN_START_DATE = '2009-01-01'
TRAIN_END_DATE = '2020-07-01'
TRADE_START_DATE = '2020-07-01'
TRADE_END_DATE = '2022-12-01'
# TRADE_END_DATE = '2023-05-01'

df_dji = YahooDownloader(start_date = TRADE_START_DATE,
                     end_date = TRADE_END_DATE,
                     ticker_list = ['^dji']).fetch_data()

C:\Users\ASUS\Desktop\Finance\RL\venv\lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

Shape of DataFrame:  (610, 8)


In [171]:
df_dji = df_dji[['date','close']]
fst_day = df_dji['close'][0]
dji = pd.merge(df_dji['date'], df_dji['close'].div(fst_day).mul(1000000),
               how='outer', left_index=True, right_index=True).set_index('date')

In [194]:
df_result_a2c = df_account_value_a2c.set_index(df_account_value_a2c.columns[0]) if if_using_a2c else None
df_result_ddpg = df_account_value_ddpg.set_index(df_account_value_ddpg.columns[0]) if if_using_ddpg else None
df_result_ppo = df_account_value_ppo.set_index(df_account_value_ppo.columns[0]) if if_using_ppo else None
df_result_td3 = df_account_value_td3.set_index(df_account_value_td3.columns[0]) if if_using_td3 else None
df_result_sac = df_account_value_sac.set_index(df_account_value_sac.columns[0]) if if_using_sac else None

result = pd.DataFrame()
if if_using_a2c: result = pd.merge(result, df_result_a2c, how='outer', left_index=True, right_index=True)
# if if_using_ddpg: result = pd.merge(result, df_result_ddpg, how='outer', left_index=True, right_index=True)
if if_using_ppo: result = pd.merge(result, df_result_ppo, how='outer', left_index=True, right_index=True)
# if if_using_td3: result = pd.merge(result, df_result_td3, how='outer', left_index=True, right_index=True)
if if_using_sac: result = pd.merge(result, df_result_sac, how='outer', left_index=True, right_index=True)



In [195]:
# Merge dataframes and view results

col_name = []
col_name.append('A2C') if if_using_a2c else None
# col_name.append('DDPG') if if_using_ddpg else None
col_name.append('PPO') if if_using_ppo else None
# col_name.append('TD3') if if_using_td3 else None
col_name.append('SAC') if if_using_sac else None

result.columns = col_name

In [196]:
result = pd.merge(result, MVO_result, how='outer', left_index=True, right_index=True)
result = pd.merge(result, dji, how='outer', left_index=True, right_index=True).fillna(method='bfill')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17972\3181995248.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  result = pd.merge(result, dji, how='outer', left_index=True, right_index=True).fillna(method='bfill')


In [197]:
result

A2C           PPO           SAC      Mean Var  \
date                                                                 
2020-07-01  1.000000e+06  1.000000e+06  1.000000e+06  1.012656e+06   
2020-07-02  1.000305e+06  1.000012e+06  1.000102e+06  1.014485e+06   
2020-07-06  1.002702e+06  1.000231e+06  1.000385e+06  1.048137e+06   
2020-07-07  9.997840e+05  1.000074e+06  9.990859e+05  1.037411e+06   
2020-07-08  1.002826e+06  1.000385e+06  9.997949e+05  1.059415e+06   
...                  ...           ...           ...           ...   
2022-11-23  1.236618e+06  1.103535e+06  1.320976e+06  1.247230e+06   
2022-11-25  1.228017e+06  1.093084e+06  1.333216e+06  1.236456e+06   
2022-11-28  1.209760e+06  1.075388e+06  1.306336e+06  1.212838e+06   
2022-11-29  1.203575e+06  1.066478e+06  1.299648e+06  1.192015e+06   
2022-11-30           NaN           NaN           NaN           NaN   

                   close  
date                      
2020-07-01  1.000000e+06  
2020-07-02  1.003590e+06  
2020-07-06  1.021452e+06  
2020-07-07  1.006031e+06  
2020-07-08  1.012913e+06  
...                  ...  
2022-11-23  1.328700e+06  
2022-11-25  1.334644e+06  
2022-11-28  1.315310e+06  
2022-11-29  1.315429e+06  
2022-11-30  1.344077e+06  

[610 rows x 5 columns]

In [198]:
# Plot results
import os
import matplotlib.pyplot as plt
plots_path = '../plots'
plt.rcParams["figure.figsize"] = (15,5)
plt.figure()
result.plot()

plt.title('Portfolio Value Comparison')
plt.ylabel('Portfolio Value')
plt.xlabel('Date')
plt.legend(loc='upper left')
# Save the plot to a file (e.g., PNG)
plt.savefig(os.path.join(plots_path, 'portfolio_value_comparison_second.png'))
plt.show()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17972\2224680192.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
